repos:
  - repo: local
    hooks:
      - id: run-secret-searcher
        name: Run Secret Searcher check on staged files
        entry: python3 src/cli.py run
        language: python
        always_run: true
        pass_filenames: true
        additional_dependencies: [ click, PyYAML, pandas, tensorflow, scikit-learn ]
