repos:
  - repo: local
    hooks:
      - id: finney
        name: Run FINNEY on staged files
        entry: finney run
        language: python
        always_run: true
        pass_filenames: true
        additional_dependencies: [ click, PyYAML, pandas, rich ]
