repos:
  - repo: local
    hooks:
      - id: run-secret-searcher
        name: Run Secret Searcher check on staged files
        entry: python3 src/cli.py
        language: system
        always_run: true
        pass_filenames: true

