repos:
  - repo: local
    hooks:
      - id: run-finney
        name: Run FINNEY on staged files
        entry: python3 src/cli.py run
        language: python
        always_run: true
        pass_filenames: true
        additional_dependencies: [ click, PyYAML, pandas, scikit-learn, rich, xgboost==3.0.4 ]
